spring:
  profiles:
    active: ${PROFILES_ACTIVE:dev}
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:}:${DATASOURCE_PORT:}/${DATASOURCE_TARGET:}?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:}
    password: ${DATASOURCE_PASSWORD:}

management:
  endpoints:
    web:
      exposure:
        include: '*'

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.springcloud.sysadmin.organization.remote
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
    dispatcher: all
    threadPool: cached
    threads: 10

  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
    # 配置启动检查,没有提供者的时候报错，如果没有调用提供者，那么可以忽略,默认是true
  reference:
    check: true
  cloud:
    subscribed-services: organization

logging:
  level:
    com.springcloud: debug
    org.springframework.web: info
    org.springframework.security: debug