spring:
  profiles:
    active: dev
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: organization
  protocol:
    name: dubbo
    port: -1

