version: "3.9"
services:
  gateway_web:
    ports:
      - "8180:8180"
    image: '192.168.1.98:5000/gateway-web:latest'
    env_file:
      - server.env
    environment:
      TZ: Asia/Shanghai
    entrypoint: "java -jar -Xmx512m /root/app.jar"
