version: "3.9"
services:
  organization:
    ports:
      - "8182:8182"
    image: '192.168.1.98:5000/organization:latest'
    env_file:
      - server.env
    environment:
      TZ: Asia/Shanghai
    entrypoint: "java -jar -Xmx512m /root/app.jar"
